name: Angular Build and Deploy

on:
  push:
    branches:
    - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build:prod

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run tests with coverage
        run: ng test --code-coverage

      #  Compares two code coverage files and generates report as a comment
      - name: Generate Code Coverage report
        id: code-coverage
        uses: barecheck/code-coverage-action@v1
        with:
          barecheck-github-app-token: ${{ secrets.BARECHECK_GITHUB_APP_TOKEN }}
          lcov-file: "./coverage/lcov.info"
          base-lcov-file: "./lcov.info"
          minimum-ratio: 0 # Fails Github action once code coverage is decreasing
          send-summary-comment: true
          show-annotations: "warning" # Possible options warning|error

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_S3_MATTPITTS_SITE_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_S3_MATTPITTS_SITE_ACCESS_KEY_SECRET }}
        aws-region: us-east-2

    - name: Deploy
      if: success()
      run: aws s3 sync ./dist/mattpitts-site/browser s3://matt.gopitts.net
